# vim: nospell

clone_folder: "c:\\cuda"

skip_commits:
  message: /\[ci skip\]/

environment:
  global:
    STACK_ROOT: "c:\\sr"
  matrix:
    - GHC: "9.10"
    - GHC: "9.6"
    - GHC: "9.0"
    - GHC: "8.4"

before_build:
  # http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - set PATH=C:\Users\appveyor\AppData\Roaming\local\bin;%PATH%

  # install CUDA-13.0
  - appveyor DownloadFile "https://developer.download.nvidia.com/compute/cuda/13.0.2/network_installers/cuda_13.0.2_windows_network.exe" -FileName install_cuda.exe
  - install_cuda.exe -s compiler_13.0 cudart_13.0 cublas_13.0 cublas_dev_13.0 cufft_13.0 cufft_dev_13.0 cusolver_13.0 cusolver_dev_13.0 cusparse_13.0 cusparse_dev_13.0
  - set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v13.0\nvvm\bin;%PATH%
  - set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v13.0\bin;%PATH%
  - nvcc --version

  # CUDA refuses to install the driver if no compatible GPU can be found, so
  # copy these .dll files manually
  # - appveyor DownloadFile "https://drive.google.com/uc?export=download&id=14x0RX8QlHQ6vKhimbR4FDRgfP7EoHfgc" -FileName nvdriver-9.0.176.7z
  # - 7z x nvdriver-9.0.176.7z -oC:\Windows\System32

  # install stack
  - appveyor DownloadFile "https://www.stackage.org/stack/windows-x86_64" -FileName stack.zip
  - 7z x stack.zip stack.exe
  - stack --version

  - ln -s stack-%GHC%.yaml stack.yaml
  - stack setup --no-terminal > NUL
  - stack build --no-terminal --no-copy-bins --fast --jobs=1 --only-dependencies --test --no-run-tests --haddock --no-haddock-deps

build_script:
  - stack build --no-terminal --fast --test --no-run-tests

test_script:
  - stack test

