# vim: nospell

clone_folder: "c:\\cuda"

skip_commits:
  message: /\[ci skip\]/

environment:
  global:
    STACK_ROOT: "c:\\sr"
  matrix:
    - GHC: "8.6"
    - GHC: "8.4"
    - GHC: "8.2"
    - GHC: "8.0"
    - GHC: "7.10"
    # - GHC: "7.8"  # failed to install ghc: https://ci.appveyor.com/project/tmcdonell/cuda/build/1.0.4/job/ufhtj0klyq73psas#L149

before_build:
  # http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - set PATH=C:\Users\appveyor\AppData\Roaming\local\bin;%PATH%

  # install CUDA-9.0
  - appveyor DownloadFile "https://developer.nvidia.com/compute/cuda/9.0/Prod/network_installers/cuda_9.0.176_windows_network-exe" -FileName install_cuda.exe
  - install_cuda.exe -s compiler_9.0 cudart_9.0 cublas_9.0 cublas_dev_9.0 cufft_9.0 cufft_dev_9.0 cusolver_9.0 cusolver_dev_9.0 cusparse_9.0 cusparse_dev_9.0
  - set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v9.0\nvvm\bin;%PATH%
  - set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;%PATH%
  - nvcc --version

  # CUDA refuses to install the driver if no compatible GPU can be found, so
  # copy these .dll files manually
  - appveyor DownloadFile "https://drive.google.com/uc?export=download&id=14x0RX8QlHQ6vKhimbR4FDRgfP7EoHfgc" -FileName nvdriver-9.0.176.7z
  - 7z x nvdriver-9.0.176.7z -oC:\Windows\System32

  # install stack
  - appveyor DownloadFile "https://www.stackage.org/stack/windows-x86_64" -FileName stack.zip
  - 7z x stack.zip stack.exe
  - stack --version

  - ln -s stack-%GHC%.yaml stack.yaml
  - stack setup --no-terminal > NUL
  - stack build --no-terminal --no-copy-bins --fast --jobs=1 --only-dependencies --test --no-run-tests --haddock --no-haddock-deps

build_script:
  - stack build --no-terminal --fast --test --no-run-tests

test_script:
  - stack test

